import Account from './Account'
import Accueil from './Accueil'
import Animation from './Animation'
import AnimationCreation from './AnimationCreation'
import CaracterCard from './CaracterCard'
import Informations from './Informations'
import InteractiveMap from './InteractiveMap'
import VoluntaryInterface from './VoluntaryInterface'
import Quest from './Quest'
import MimbleMimbus from './MimbleMimbus'
import ListAnimations from './ListAnimations'
import Tickets from './Tickets'
import Login from './Login'
import GenerateMigration from './GenerateMigration'

export default { Login ,Account, Accueil, Animation, AnimationCreation, CaracterCard, Informations, InteractiveMap, VoluntaryInterface, Quest, MimbleMimbus, ListAnimations, Tickets, GenerateMigration }
