import Account from './Account'
import Accueil from './Accueil'
import Animation from './Animation'
import AnimationCreation from './AnimationCreation'
import CaracterCard from './CaracterCard'
import Informations from './Informations'
import InteractiveMap from './InteractiveMap'
import VoluntaryInterface from './VoluntaryInterface'
import MimbleMimbus from './MimbleMimbus'
import ListAnimations from './ListAnimations'
import Tickets from './Tickets'
import Login from './Login'
import GenerateMigration from './GenerateMigration'
import NotFound from './NotFound'
import Quests from './Quests'
import QuestDetails from './QuestDetails'

export default { Login, Account, Accueil, Animation, AnimationCreation, CaracterCard, Informations, InteractiveMap, VoluntaryInterface, MimbleMimbus, ListAnimations, Tickets, GenerateMigration, NotFound, Quests, QuestDetails }
